id: I5E6DA852
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T22:53:20+00:00'
last_modified: '2022-06-09T04:43:30.607205+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1988
  title: མི་ལ་རས་པའི་རྣམ་མགུར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '0404':
      image_group_id: I1CZ2041
      title: Volume 1 of mi la ras pa'i rnam mgur
      total_pages: 300
      order: 1
      base_file: 0404.txt
    E5EF:
      image_group_id: I1CZ2042
      title: Volume 2 of mi la ras pa'i rnam mgur
      total_pages: 640
      order: 2
      base_file: E5EF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
