id: I5E6DA852
legacy_id: P007086
ocr_import_info:
  bdrc_scan_id: W1CZ1988
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T22:49:17'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T19:09:52.548573+00:00'
last_modified: 2022-08-31 03:11:09.680251
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ1988
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ1988
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མི་ལ་རས་པའི་རྣམ་མགུར།
  author: གཙང་སྨྱོན་ཧེ་རུ་ཀ་རུས་པའི་རྒྱན་ཅན།
statistics:
  ocr_word_mean_confidence_index: 0.7126013376492699
  ocr_word_median_confidence_index: 0.800000011920929
quality: null
bases:
  I1CZ2041:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2041
      total_pages: 300
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ2041.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.710121274943658
    legacy_id: v001
  I1CZ2042:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2042
      total_pages: 640
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1CZ2042.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.7134082484943846
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
