id: P007086
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1988
  title: མི་ལ་རས་པའི་རྣམ་མགུར
  author: ''
  volumes:
    12ec2ce3cbc14c16afdd49ac0ebaf992:
      image_group_id: I1CZ2041
      title: Volume 1 of mi la ras pa'i rnam mgur
      volume_number: 1
      total_pages: 300
      base_file: v001.txt
    8d0012ea5a304b5ca87e2d2923b3781c:
      image_group_id: I1CZ2042
      title: Volume 2 of mi la ras pa'i rnam mgur
      volume_number: 2
      total_pages: 640
      base_file: v002.txt
ebook_metadata:
  title: མི་ལ་རས་པའི་རྣམ་མགུར
  author: ''
  sku: P007086
  cover: cover.jpg
  layers:
  - pagination
