id: P007086
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1988
  title: མི་ལ་རས་པའི་རྣམ་མགུར
  author: ''
  volumes:
    ff454dffeec34890a8a65ca856e01f7b:
      image_group_id: I1CZ2041
      title: ''
      volume_number: 1
      total_pages: 300
    e93f5537e6d3450f915329e74c7dbc0a:
      image_group_id: I1CZ2042
      title: ''
      volume_number: 2
      total_pages: 640
ebook_metadata:
  title: མི་ལ་རས་པའི་རྣམ་མགུར
  author: ''
  sku: P007086
  cover: cover.jpg
  layers:
  - pagination
